name: kisisel_ai_asistan
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.6.0
  cupertino_icons: ^1.0.8
  google_generative_ai: ^0.4.7
  path_provider: ^2.1.5
  flutter_local_notifications: ^18.0.1
  timezone: ^0.9.4
  permission_handler: ^11.3.1
  shared_preferences: ^2.3.3
  crypto: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  # İkon paketi buraya eklendi
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  
  # Resim yolu burada tanımlı
  assets:
    - assets/logo.png

# İKON YAPILANDIRMASI (Dosyanın en soluna yaslı olmalı)
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  # Senin assets kısmında "logo.png" yazdığı için burayı da öyle yaptım.
  # Eğer resmin adı farklıysa burayı düzelt.
  image_path: "assets/logo.png" 
  min_sdk_android: 21
  windows: true # Windows ikonunu da değiştirir